# Configuration PostgreSQL

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: deploy
  password: dabakh
  host: localhost

development:
  <<: *default
  database: yembal2_development

test:
  <<: *default
  database: yembal2_test

production:
  <<: *default
  database: yembal2_production
  username: deploy
  password: dabakh
